services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hpc_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hpc-network

  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/hpc_app
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - hpc-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - HOST=0.0.0.0
      - PORT=5173
    depends_on:
      - api
    networks:
      - hpc-network




volumes:
  postgres_data:

networks:
  hpc-network:
    driver: bridge
